import type { Chapter } from './types.ts';

/**
 * Part 2 — 디자인 요소 (7–13장). 『Design Basics』 9판(Pentak & Lauer, 2016) 기준 쪽수.
 * 설명은 모두 직접 정리한 요약이다.
 */
export const elementChapters: Chapter[] = [
  {
    id: 'line',
    no: 7,
    part: 'element',
    ko: '선',
    en: 'Line',
    pages: [126, 149],
    oneLine: '움직이는 점 — 가장자리를 그리고, 손의 경로를 기록하고, 시선을 이끈다.',
    summary:
      '선은 점이 움직인 자취이자 가장 익숙한 요소다. 윤곽 · 단면 윤곽 · 제스처처럼 그려진 선뿐 아니라, 화면의 기하학에 숨은 내재된 선, 점과 시선을 잇는 암시된 선 · 심리적 선도 구도를 이끈다. 선의 방향과 질은 감정과 움직임을 전하고, 촘촘히 모이면 명도를 만든다.',
    weeks: ['WK02'],
    concepts: [
      { id: 'line.point-in-motion', ko: '움직이는 점', en: 'A Point Set in Motion', page: 128, body: '크기가 없는 점이 움직여 첫 번째 차원인 선이 된다(클레). 이론상 길이만 있지만 실제 미술에서는 굵기도 가진다. 형태의 가장자리이자 손이 지나간 경로의 기록이다.' },
      { id: 'line.mood', ko: '선의 성격과 감정', en: 'Lines Convey Mood and Feeling', page: 129, body: '선에는 초조한 · 화난 · 자유로운 · 차분한 · 우아한 같은 성격이 있다. 선의 질만으로도 인물의 성격이나 감정을 암시할 수 있다.' },
      { id: 'line.contour', ko: '윤곽선 드로잉', en: 'Contour Drawing', page: 130, body: '형태의 가장자리를 따라가며 외곽을 그리는 가장 흔한 선의 쓰임.' },
      { id: 'line.cross-contour', ko: '단면 윤곽선', en: 'Cross Contour', page: 130, body: '입체를 자른 단면의 경계를 따라 표면을 감싸는 선. 지형도의 등고선, 나무껍질의 가로 줄무늬처럼 외곽선이 아닌 방식으로 부피를 보여 준다.' },
      { id: 'line.gesture', ko: '제스처 드로잉', en: 'Gesture Drawing', page: 132, body: '형태 묘사보다 동작 · 무게 · 자세를 잡는 드로잉. 선이 가장자리에 머물지 않고 형태 안을 자유롭게 오가며, 빠르고 즉흥적으로 그려진다.' },
      { id: 'line.inherent', ko: '내재된 선', en: 'Inherent Line', page: 134, body: '직사각형 화면의 기하학 — 중심선, 대각선, 그 교차점 — 에 숨어 있는 구조선. 보이지 않아도 구도의 토대가 된다.' },
      { id: 'line.implied', ko: '암시된 선', en: 'Implied Line', page: 136, body: '점이나 요소를 일정하게 놓으면 눈이 자동으로 그것들을 잇는다. 실제로 그려지지 않은 선이 시선을 안내한다.' },
      { id: 'line.psychic', ko: '심리적 선', en: 'Psychic Line', page: 136, body: '인물이 바라보는 방향을 따라 관람자의 시선이 이어지는 선. 사람 사이의 연결을 만든다.' },
      { id: 'line.direction', ko: '선의 방향', en: 'Line Direction', page: 138, body: '수평선은 휴식과 고요, 수직선은 잠재된 활동, 대각선은 가장 강한 움직임을 암시한다. 수평 · 수직선은 화면 테두리와 평행해 움직임을 누그러뜨린다.' },
      { id: 'line.quality', ko: '선의 질', en: 'Line Quality', page: 140, body: '굵기 · 거칠기 · 속도의 변화로 다양성과 강조를 만든다. 떨리는 선은 공포를, 굵기의 변화는 데이터(나폴레옹 원정 도표)까지 전한다.' },
      { id: 'line.value', ko: '명도로서의 선', en: 'Line as Value', page: 142, body: '선을 촘촘히 겹치면 회색 영역(명도)이 생긴다. 해칭 · 크로스해칭으로 윤곽선만으로는 없던 입체감을 만든다.' },
      { id: 'line.painting', ko: '회화 속 선', en: 'Line in Painting', page: 144, body: '형태를 윤곽으로 묶는 회화와 색면으로 짓는 회화. 선은 대상을 묘사하기도, 붓질 자체로 독립하기도(명시적 제스처 선) 한다.' },
      { id: 'line.lost-found', ko: '사라졌다 나타나는 윤곽', en: 'Lost-and-Found Contour', page: 148, body: '윤곽의 일부만 날카롭게 드러나고 나머지는 어둠이나 배경으로 사라지는 표현. 관람자의 눈이 빈 곳을 완성하며, 상대적 명료성이 오히려 실제 지각에 가깝다.' },
    ],
    pitfalls: [
      { title: '그려진 선만 선이 아니다', body: '시선(심리적 선), 점의 배열(암시된 선), 화면의 대각선(내재된 선)도 모두 선이다. ‘시선이 흐른다’고 썼다면 어떤 선이 시선을 이끄는지 이름 붙일 수 있다.' },
      { title: '제스처는 선의 유형', body: '수업 표현 ‘제스처’는 7장의 제스처 드로잉(동작을 잡는 빠른 선)과 11장의 움직임 암시 둘 다와 이어진다.' },
    ],
    questions: ['선이 형태를 묘사하는가(윤곽), 움직임을 잡는가(제스처)?', '보이지 않는 선(암시된 · 심리적 · 내재된 선)이 시선을 이끄는가?', '주된 방향은 수평 · 수직 · 대각선 중 무엇인가?', '선의 굵기와 속도는 어떤 감정을 주는가?'],
    quiz: [
      { q: '윤곽선 드로잉과 제스처 드로잉의 차이는?', a: '윤곽선은 형태의 가장자리를 정확히 따라가고, 제스처는 동작 · 무게 · 자세를 빠르게 잡으며 선이 형태 안을 오간다.' },
      { q: '심리적 선(psychic line)이란?', a: '인물의 시선 방향을 따라 관람자의 눈이 이어 그리는 보이지 않는 선.' },
      { q: '가장 강한 움직임을 암시하는 선의 방향은?', a: '대각선.' },
    ],
  },
  {
    id: 'shape',
    no: 8,
    part: 'element',
    ko: '형태',
    en: 'Shape',
    pages: [150, 177],
    oneLine: '선으로 둘러싸이거나 색 · 명도의 변화로 가장자리가 생긴, 눈에 보이는 영역.',
    summary:
      '형태는 형(figure)과 바탕(ground)을 가르는 경계의 지각에서 시작한다. 자연주의 · 이상주의 · 왜곡 · 추상 · 비대상으로 대상과의 거리를 조절하고, 곡선형과 직선형으로 성격을 정한다. 남은 공간(음형)도 설계 대상이며, 양형과 음형이 섞이면 통합되고 같은 긴장을 가지면 모호해진다.',
    weeks: ['WK01'],
    concepts: [
      { id: 'shape.shape-form', ko: '형태(shape)와 형식(form)', en: 'Shape and Form', page: 152, body: '둘 다 ‘형태’로 쓰이지만, form은 색 · 질감 · 구성을 포함한 전체 시각 조직을 뜻하기도 하므로 낱낱의 형태는 shape라 부르는 편이 정확하다.' },
      { id: 'shape.figure-ground', ko: '형과 바탕', en: 'Figure and Ground', page: 152, body: '지각은 형과 바탕을 가르는 경계를 알아보는 데서 시작한다. 다른 조건이 같다면 볼록한 형태는 형으로, 오목한 형태는 바탕으로 읽히는 경향이 있다.' },
      { id: 'shape.volume-mass', ko: '부피와 양감', en: 'Volume/Mass', page: 156, body: '2차원의 형태(shape)에 대응하는 3차원 개념. 실루엣은 하나의 입체가 만들 수 있는 수많은 형태 중 하나일 뿐이다.' },
      { id: 'shape.naturalism', ko: '자연주의', en: 'Naturalism', page: 158, body: '대상을 실제로 보이는 그대로 옮기는 태도.' },
      { id: 'shape.idealism', ko: '이상주의', en: 'Idealism', page: 158, body: '세상을 있는 그대로가 아니라 ‘그래야 한다’고 여기는 완벽의 기준에 맞춰 고쳐 그리는 왜곡. 광고 속 인물도 일상적인 이상주의다.' },
      { id: 'shape.distortion', ko: '왜곡 · 과장된 형태', en: 'Distortion (Exaggerated Shapes)', page: 160, body: '형태를 늘이고 줄여 비례를 바꾸는 표현. 캐리커처처럼 닮음을 유지하거나, 엘 그레코의 길게 늘인 몸처럼 감정을 강조한다.' },
      { id: 'shape.abstraction', ko: '추상', en: 'Abstraction', page: 162, body: '자연 형태를 본질적이고 기본적인 성격으로 단순화하는 왜곡. 세부를 버리고 원 · 삼각형 · 사각형 같은 기본 도형으로 환원한다.' },
      { id: 'shape.biomorphic', ko: '생물형태', en: 'Biomorphic Shapes', page: 163, body: '자연의 유기적 형태를 떠올리게 하지만 이름 붙일 수 있는 대상을 닮지는 않은 추상 형태.' },
      { id: 'shape.nonobjective', ko: '비대상 형태', en: 'Nonobjective Shapes', page: 164, body: '참조하는 대상이 전혀 없는 순수한 형태. 자연을 단순화한 ‘추상’과 구분한다.' },
      { id: 'shape.curvilinear', ko: '곡선형', en: 'Curvilinear Shapes', page: 166, body: '몸과 자연을 연상시키는 둥근 형태. 공간에 흐름과 움직임을 만든다.' },
      { id: 'shape.rectilinear', ko: '직선형', en: 'Rectilinear Shapes', page: 168, body: '직각과 곧은 모서리로 이루어진 형태. 이성적이고 제작된 느낌을 준다. 대부분의 디자인은 곡선형과 직선형을 조합한다.' },
      { id: 'shape.positive-negative', ko: '양형과 음형', en: 'Positive/Negative Shapes', page: 170, body: '같은 형태라도 어디에 놓이느냐에 따라 남은 공간(음형)의 모양이 달라진다. 음형도 형만큼 신중하게 설계해야 한다.' },
      { id: 'shape.integration', ko: '양형 · 음형의 통합', en: 'Integration', page: 172, body: '형과 바탕이 너무 엄격히 갈리면 ‘오려 붙인’ 느낌이 난다. 명도와 경계를 섞어 형과 바탕이 오가게 하면 화면이 통합된다.' },
      { id: 'shape.ambiguity', ko: '모호성(형 · 바탕 반전)', en: 'Ambiguity', page: 176, body: '양형과 음형이 같은 긴장을 가져 눈이 어느 쪽을 형으로 볼지 골라야 하는 상태. 두 읽기를 동시에 할 수는 없다.' },
    ],
    pitfalls: [
      { title: '추상과 비대상', body: '자연에서 출발해 단순화했다면 추상, 아무것도 참조하지 않는 순수 도형이면 비대상이다.' },
      { title: '‘유기적’이라는 말', body: '수업 표현 ‘유기적’은 책에서 곡선형 · 생물형태와 연결된다. 무엇이 유기적으로 보이게 하는지(곡선, 성장하는 방향, 불규칙한 윤곽)를 함께 쓴다.' },
    ],
    questions: ['형과 바탕은 분명히 갈리는가, 오가는가?', '자연주의 · 이상주의 · 왜곡 · 추상 · 비대상 중 어디쯤인가?', '곡선형과 직선형 중 무엇이 지배하는가?', '남은 공간(음형)은 어떤 모양인가?'],
    quiz: [
      { q: '추상과 비대상의 차이는?', a: '추상은 자연 형태를 단순화한 것, 비대상은 참조 대상이 전혀 없는 순수 형태.' },
      { q: '생물형태(biomorphic)란?', a: '유기적 자연 형태를 암시하지만 특정 대상을 닮지 않은 추상 형태.' },
      { q: '형 · 바탕 모호성에서 우리가 할 수 없는 것은?', a: '두 읽기를 동시에 보는 것. 눈은 한 번에 하나만 고른다.' },
    ],
  },
  {
    id: 'texture',
    no: 9,
    part: 'element',
    ko: '패턴과 질감',
    en: 'Pattern and Texture',
    pages: [178, 193],
    oneLine: '표면의 성질 — 패턴은 규칙적인 반복, 질감은 촉각을 불러오는 표면.',
    summary:
      '패턴은 모티프의 반복으로, 빈 곳을 채우려는 욕구에서 시작해 테셀레이션 같은 기하학적 질서로 발전한다. 질감은 표면의 성질로, 기억 속 촉각을 불러온다. 실제로 만질 수 있는 촉각적 질감과 눈으로만 느끼는 시각적 질감이 있으며, 극단의 시각적 질감은 트롱프뢰유다.',
    weeks: ['WK01'],
    concepts: [
      { id: 'texture.pattern', ko: '패턴', en: 'Pattern', page: 180, body: '디자인 모티프의 반복. 빈 공간을 채우려는 본능(horror vacui)에서 출발하며, 작은 패턴 조각만으로도 시선을 끄는 초점이 될 수 있다.' },
      { id: 'texture.tessellation', ko: '테셀레이션', en: 'Tessellation', page: 182, body: '단위 형태를 밀거나 돌려 틈 · 겹침 없이 평면을 채우는 예측 가능한 패턴. 그리드로 환원되며 결정형 질서를 갖는다.' },
      { id: 'texture.vs-pattern', ko: '질감과 패턴의 차이', en: 'Texture and Pattern', page: 184, body: '둘 다 표면의 성질이다. 패턴은 같은 모티프의 규칙적 반복, 질감은 덜 규칙적인 반복이며 촉각을 불러온다. 가까이 찍은 천의 패턴이 나무껍질 질감처럼 보이기도 한다.' },
      { id: 'texture.texture', ko: '질감', en: 'Texture', page: 186, body: '대상 표면의 성질. 만지지 않아도 명암 패턴을 단서로 기억 속 촉감이 떠오른다. 매끈함도 하나의 질감이다.' },
      { id: 'texture.tactile', ko: '촉각적 질감', en: 'Tactile Texture', page: 188, body: '실제로 만질 수 있는 질감. 조각 · 건축의 표면, 물감을 두껍게 바른 임파스토가 여기에 해당한다.' },
      { id: 'texture.implied', ko: '암시된 질감', en: 'Implied Texture', page: 189, body: '실제 표면은 매끈하지만 질감의 이미지만 보이는 경우(인쇄된 붓자국).' },
      { id: 'texture.collage', ko: '콜라주', en: 'Collage', page: 190, body: '색지 · 천 · 버려진 재료를 붙여 만드는 기법. 재료를 묘사하지 않고 직접 다루며, 하찮은 재료를 매력적인 질감으로 바꾼다.' },
      { id: 'texture.visual', ko: '시각적 질감', en: 'Visual Texture', page: 192, body: '평평한 표면 위에 질감의 인상만 만든 것. 익숙한 질감의 색과 명암 패턴을 재현해 ‘진짜 같음(핍진성, verisimilitude)’을 얻는다.' },
      { id: 'texture.trompe-loeil', ko: '트롱프뢰유', en: "Trompe L'oeil", page: 192, body: '‘눈을 속인다’는 뜻의 극단적 시각적 질감. 얕은 부조처럼 거의 평평한 대상일 때 가장 설득력 있다.' },
    ],
    pitfalls: [
      { title: '사진 속 질감은 시각적 질감', body: '사진이나 렌더링에서 ‘만져질 듯한 질감’은 실제로 만질 수 없으니 시각적 질감이다. 그 질감이 어떤 명암 패턴으로 만들어졌는지(거친 입자, 반사, 부식된 얼룩)를 함께 쓴다.' },
      { title: '노이즈 · 그레인', body: '거친 입자(노이즈)는 화면 전체에 고르게 퍼지면 시각적 질감이자 올오버 패턴처럼 작동한다.' },
    ],
    questions: ['표면이 규칙적으로 반복되는가(패턴), 불규칙한가(질감)?', '질감은 실제로 만질 수 있는가(촉각적), 눈으로만 느껴지는가(시각적)?', '질감이 초점 · 균형 · 통일에 어떤 역할을 하는가?'],
    quiz: [
      { q: '촉각적 질감과 시각적 질감의 차이는?', a: '촉각적 질감은 실제로 만질 수 있고, 시각적 질감은 평면 위에 질감의 인상만 재현한 것이다.' },
      { q: '테셀레이션이란?', a: '단위 형태를 이동 · 회전해 틈이나 겹침 없이 평면을 채우는 패턴.' },
      { q: '트롱프뢰유가 가장 설득력 있는 대상은?', a: '얕은 부조처럼 거의 평평한 대상.' },
    ],
  },
  {
    id: 'space',
    no: 10,
    part: 'element',
    ko: '공간의 환영',
    en: 'Illusion of Space',
    pages: [194, 227],
    oneLine: '평평한 화면에 깊이를 만드는 단서들.',
    summary:
      '2차원 화면의 공간은 환영이다. 크기 · 겹침 · 수직 위치 · 대기 원근 · 선원근이 깊이의 단서가 되고, 증폭된 원근 · 다시점 · 축측 투영은 다른 방식의 공간을 만든다. 화면 안에 담기느냐(닫힌 형식) 밖으로 이어지느냐(열린 형식), 겹친 것이 다 보이느냐(투명성)도 공간을 결정한다.',
    weeks: ['WK01', 'WK02'],
    concepts: [
      { id: 'space.picture-plane', ko: '화면과 깊이', en: 'Picture Plane', page: 196, body: '그림 평면은 평평하지만, 공간의 단서를 쓰면 창문처럼 그 너머의 3차원 세계로 보인다. 화면의 평면성을 살릴지 깊이를 만들지는 선택이다.' },
      { id: 'space.size', ko: '크기', en: 'Size', page: 198, body: '멀수록 작아 보인다는 경험을 이용한 가장 쉬운 깊이 단서. 같은 형태를 다른 크기로 반복하면 효과가 더 크다.' },
      { id: 'space.overlapping', ko: '겹침', en: 'Overlapping', page: 200, body: '앞의 것이 뒤의 것을 가려 앞뒤를 알린다. 겹침만 쓰면 공간이 얕고, 크기 변화와 함께 쓰면 깊어진다.' },
      { id: 'space.vertical-location', ko: '수직 위치', en: 'Vertical Location', page: 202, body: '화면에서 높이 놓일수록 멀리 있는 것으로 읽힌다. 아시아 · 근동 미술에서 널리 쓰였다.' },
      { id: 'space.aerial', ko: '대기 원근', en: 'Aerial (Atmospheric) Perspective', page: 204, body: '멀어질수록 명도 대비와 윤곽이 약해지고 색이 하늘빛을 띤다. 대비가 큰 것은 앞으로, 약한 것은 뒤로 물러난다.' },
      { id: 'space.linear', ko: '선원근법', en: 'Linear Perspective', page: 208, body: '평행선이 멀어지며 눈높이(수평선)의 소실점으로 모인다. 한 눈, 한 고정 시점을 전제하므로 인위적인 느낌도 준다. 원은 타원으로 보인다.' },
      { id: 'space.one-point', ko: '1점 투시', en: 'One-Point Perspective', page: 210, body: '화면에 수직인 선들이 하나의 소실점으로 모인다. 정돈되고 통일된 공간, 앞으로 나아가는 은유를 만든다.' },
      { id: 'space.two-point', ko: '2점 투시', en: 'Two-Point Perspective', page: 212, body: '대상을 비스듬히 볼 때 모서리들이 수평선 위 두 소실점으로 모인다. 1점 투시보다 자연스럽다.' },
      { id: 'space.multipoint', ko: '다점 투시', en: 'Multipoint Perspective', page: 214, body: '세 번째 소실점으로 높이감을 주거나, 서로 다른 각도의 대상마다 소실점을 두어 역동적인 공간을 만든다.' },
      { id: 'space.amplified', ko: '증폭된 원근', en: 'Amplified Perspective', page: 216, body: '대상이 관람자를 정면으로 향할 때 생기는 극적인 단축. 내민 손가락이나 발이 몸에 비해 엄청나게 크게 보이며, 화면 밖으로 튀어나올 듯한 역동을 만든다.' },
      { id: 'space.multiple', ko: '다시점', en: 'Multiple Perspective', page: 218, body: '여러 시점에서 본 모습을 한 이미지에 합친다(이집트 벽화, 입체파). 움직이는 눈으로 보는 방식에 가깝다.' },
      { id: 'space.axonometric', ko: '축측 투영', en: 'Axonometric Projection', page: 220, body: '사선으로 깊이를 나타내되 평행선이 소실점으로 모이지 않고 평행을 유지하는 방식. 건축 · 기계 도면에 쓰인다.' },
      { id: 'space.open-closed', ko: '열린 형식과 닫힌 형식', en: 'Open Form/Closed Form', page: 222, body: '닫힌 형식은 모든 요소를 화면 안에 담아 형식적이고 구조적인 인상을, 열린 형식은 요소가 테두리에 잘리거나 밖으로 이어져 즉흥적이고 순간적인 인상을 준다.' },
      { id: 'space.transparency', ko: '투명성과 모호한 공간', en: 'Transparency (Equivocal Space)', page: 224, body: '겹친 형태들이 모두 보여 어느 것이 앞인지 정해지지 않는 공간(equivocal space). 가려져 있던 것을 드러내는 장치이기도 하다.' },
    ],
    pitfalls: [
      { title: '‘강제 원근법’ 대신 ‘증폭된 원근’', body: '강제 원근법(forced perspective)은 사진 · 영화에서 거리로 크기를 속이는 착시 기법이다. 카메라를 향해 뻗은 손이 거대해 보이는 장면은 라우어의 용어로 증폭된 원근(amplified perspective, 216쪽)이다.' },
      { title: '투과 · 엑스레이 이미지', body: '겉과 속이 함께 보이는 이미지는 10장의 투명성(모호한 공간)으로 분석할 수 있다. 겹친 층의 앞뒤가 모호해지는지를 본다.' },
    ],
    questions: ['어떤 깊이 단서가 쓰였는가 — 크기, 겹침, 수직 위치, 대기 원근, 선원근?', '시점은 어디인가(눈높이, 아래, 위, 정면으로 향하는 대상)?', '요소가 화면 안에 담기는가(닫힌), 잘려 나가는가(열린)?', '겹친 것이 다 보여 앞뒤가 모호한가(투명성)?'],
    quiz: [
      { q: '대기 원근의 두 가지 신호는?', a: '멀수록 명도 대비와 윤곽이 약해지고, 색이 하늘빛(푸른 회색)을 띤다.' },
      { q: '증폭된 원근이란?', a: '대상이 관람자를 정면으로 향할 때 생기는 극적인 단축 효과.' },
      { q: '열린 형식의 인상은?', a: '즉흥적이고 순간적이며, 화면 밖으로 이어지는 느낌.' },
    ],
  },
  {
    id: 'motion',
    no: 11,
    part: 'element',
    ko: '동세의 환영',
    en: 'Illusion of Motion',
    pages: [228, 241],
    oneLine: '움직이지 않는 화면이 움직임을 암시하는 방법.',
    summary:
      '정지된 이미지는 경험과 기억을 빌려 움직임을 암시한다. 불안정한 자세는 곧 일어날 동작을 예상하게 하고, 우리는 그 동작을 근육으로 따라 느낀다(운동감각적 공감). 반복된 인물, 잘린 인물, 흐린 윤곽, 다중 이미지와 힘의 선이 움직임을 보여 주며, 잔상과 진동하는 색은 눈 자체를 움직인다.',
    weeks: ['WK02'],
    concepts: [
      { id: 'motion.arrested', ko: '정지와 멈춘 동작', en: 'Stillness and Arrested Action', page: 230, body: '모든 것은 변하지만 그림은 한순간을 붙잡는다. 고속 촬영이나 ‘결정적 순간’의 사진은 눈으로 볼 수 없던 찰나를 오래 들여다보게 한다.' },
      { id: 'motion.anticipated', ko: '예상되는 움직임', en: 'Anticipated Motion', page: 232, body: '쓰러지기 직전의 자세, 기울어진 사각형처럼 불안정한 상태를 보면 곧 일어날 변화를 예상한다. 해소되지 않은 작은 틈(발과 받침, 공과 글러브 사이)이 긴장을 만든다.' },
      { id: 'motion.kinesthetic', ko: '운동감각적 공감', en: 'Kinesthetic Empathy', page: 232, body: '보는 동작을 우리 몸이 무의식적으로 따라 느끼는 현상. 선수가 몸을 뻗는 사진만 봐도 근육이 함께 긴장한다.' },
      { id: 'motion.repeated', ko: '반복된 인물', en: 'Figure Repeated', page: 234, body: '같은 인물을 다른 위치 · 상황에 여러 번 그려 시간의 흐름을 보여 주는 오래된 관습(스토리보드, 만화).' },
      { id: 'motion.cropped', ko: '잘린 인물', en: 'Figure Cropped', page: 235, body: '화면 테두리가 인물을 잘라 틀을 뚫고 나가는 듯한 움직임을 만든다.' },
      { id: 'motion.blurred', ko: '흐린 윤곽', en: 'Blurred Outlines', page: 236, body: '빠르게 지나가는 것은 세부와 가장자리가 사라져 흐릿하게 보인다. 느린 셔터의 사진이나 겹치는 스케치 선이 움직임을 전한다.' },
      { id: 'motion.fast-shapes', ko: '속도를 띤 형태', en: 'Fast Shapes', page: 237, body: '혜성처럼 꼬리를 끄는 형태, 길게 뻗은 유선형. 대상이 아니라 형태 자체가 속도를 말한다.' },
      { id: 'motion.multiple-image', ko: '다중 이미지', en: 'Multiple Image', page: 238, body: '한 인물의 연속된 자세를 겹쳐 보여 주면 조금씩 달라지는 위치가 움직임을 만든다(다중 노출 사진, 뒤샹).' },
      { id: 'motion.lines-of-force', ko: '힘의 선', en: 'Lines of Force', page: 238, body: '움직임의 경로를 보여 주기 위해 더한 곡선들.' },
      { id: 'motion.optical', ko: '광학적 움직임(잔상)', en: 'Optical Movement (Afterimage)', page: 240, body: '그림은 움직이지 않지만 눈은 움직인다. 그리드 교차점의 깜빡임, 강한 색을 본 뒤의 잔상, 명도가 같은 강한 색들의 진동, 모아레가 눈을 쉬지 못하게 한다.' },
    ],
    pitfalls: [
      { title: '‘시각적 잔상’과 책의 잔상', body: '책에서 잔상(afterimage)은 망막의 피로로 눈에 남는 상, 곧 광학적 움직임이다(240쪽). 움직인 대상의 흔적이 흐릿하게 남는 표현은 흐린 윤곽(236쪽)이나 다중 이미지(238쪽)라고 쓰는 편이 정확하다.' },
      { title: '‘중력’은 어떻게 쓰나', body: '중력을 거스르는 도약은 예상되는 움직임과 운동감각적 공감으로, 화면 위쪽에 무게가 실린 불안정함은 5장 균형(수직 배치)으로 설명할 수 있다.' },
    ],
    questions: ['움직임은 무엇으로 암시되는가 — 자세, 반복, 잘림, 흐림, 겹침?', '곧 일어날 동작이 예상되는가? 해소되지 않은 틈이 있는가?', '보는 내 몸이 그 동작을 따라 느끼는가(운동감각적 공감)?', '눈 자체가 흔들리는 효과(잔상, 진동, 모아레)가 있는가?'],
    quiz: [
      { q: '움직임을 암시하는 방법 네 가지는?', a: '반복된 인물, 잘린 인물, 흐린 윤곽(속도를 띤 형태), 다중 이미지(힘의 선).' },
      { q: '운동감각적 공감이란?', a: '보는 동작을 근육으로 무의식적으로 따라 느끼는 현상.' },
      { q: '책에서 말하는 잔상(afterimage)은?', a: '강한 색이나 대비를 본 뒤 망막 피로로 남는 상. 광학적 움직임의 한 종류다.' },
    ],
  },
  {
    id: 'value',
    no: 12,
    part: 'element',
    ko: '명도',
    en: 'Value',
    pages: [242, 253],
    oneLine: '빛과 어둠 — 형과 바탕을 가르고, 초점과 부피와 공간을 만든다.',
    summary:
      '명도는 밝고 어두운 정도다. 같은 회색도 주변에 따라 달라 보이며, 명도의 배치(명도 패턴)는 색과 상관없이 구도를 결정한다. 한 곳에 강한 명도 대비를 두면 초점이 되고, 그라데이션은 부피를, 대비의 강약은 공간의 앞뒤를 만든다.',
    weeks: ['WK01'],
    concepts: [
      { id: 'value.value', ko: '명도', en: 'Value', page: 244, body: '밝고 어두운 정도를 가리키는 미술 용어. 검정과 흰색만 섞은 회색은 무채색(achromatic)이라 한다.' },
      { id: 'value.contrast', ko: '명도 대비', en: 'Value Contrast', page: 244, body: '밝은 면과 어두운 면의 관계. 이웃한 명도 차가 작으면 저대비, 크면 고대비다. 같은 회색도 밝은 바탕에선 어둡게, 어두운 바탕에선 밝게 보인다.' },
      { id: 'value.pattern', ko: '명도 패턴', en: 'Value Pattern', page: 246, body: '색과 상관없이 밝음과 어둠이 어떻게, 얼마나 배치되었는지. 흑백으로 바꿔 보면 잘 보인다.' },
      { id: 'value.chiaroscuro', ko: '키아로스쿠로', en: 'Chiaroscuro', page: 246, body: '어두운 바탕에 밝은 형태를 극적으로 배치해 부피를 암시하는 명암법. 르네상스에 이름 붙었고 바로크의 극적인 장면에 잘 쓰였다.' },
      { id: 'value.color', ko: '명도와 색', en: 'Value and Color', page: 246, body: '모든 색은 명도도 가진다 — 노랑은 밝고, 보라는 어둡고, 빨강은 중간. 색으로는 균형 잡힌 그림도 흑백으로 보면 무너질 수 있다.' },
      { id: 'value.emphasis', ko: '명도에 의한 강조', en: 'Value as Emphasis', page: 248, body: '한 곳에 강한 대비를, 나머지에 약한 대비를 두면 시선이 처음 닿을 곳을 정할 수 있다.' },
      { id: 'value.space', ko: '명도와 공간', en: 'Value and Space', page: 250, body: '명암의 단계는 평면에 부피를 준다. 대비가 강한 것은 앞으로, 약한 것은 뒤로 물러나 대기 원근을 만든다. 명암으로 심리적 공간을 만들 수도 있다.' },
      { id: 'value.techniques', ko: '명암 기법', en: 'Techniques', page: 252, body: '부드러운 연필 · 목탄의 그라데이션, 크로스해칭, 물로 묽힌 워시, 점의 밀도로 만드는 시각적 회색(하프톤) 등.' },
    ],
    pitfalls: [
      { title: '‘명암 대비’ 다음 한 걸음', body: '명도 대비를 말했다면 그것이 무엇을 하는지 이어 쓴다 — 초점을 만드는가(강조), 부피를 만드는가(키아로스쿠로), 공간의 앞뒤를 만드는가(대기 원근)?' },
      { title: '실루엣', body: '세부를 지운 검은 실루엣은 명도 대비로 형과 바탕을 극단적으로 가른 형태다. 8장의 형과 바탕, 3장의 강조와 함께 쓸 수 있다.' },
    ],
    questions: ['흑백으로 보면 명도 패턴은 어떤가?', '가장 강한 명도 대비는 어디에 있으며, 그곳이 초점인가?', '명암 단계가 부피를 만드는가?', '저대비인가 고대비인가, 그 분위기는?'],
    quiz: [
      { q: '키아로스쿠로란?', a: '빛과 어둠의 극적인 대비로 부피를 암시하는 명암법.' },
      { q: '같은 회색이 다르게 보이는 이유는?', a: '주변 명도의 영향. 밝은 바탕에서는 어둡게, 어두운 바탕에서는 밝게 보인다.' },
      { q: '명도 대비와 공간의 관계는?', a: '대비가 강한 것은 앞으로, 약한 것은 뒤로 물러나 보인다(대기 원근).' },
    ],
  },
  {
    id: 'color',
    no: 13,
    part: 'element',
    ko: '색',
    en: 'Color',
    pages: [254, 289],
    oneLine: '색은 물체가 아니라 빛의 성질이며, 언제나 주변과의 관계 속에서 보인다.',
    summary:
      '색은 빛에서 온다. 빛은 섞을수록 밝아지고(가산 혼합), 물감은 섞을수록 어두워진다(감산 혼합). 색은 색상 · 명도 · 채도의 세 속성을 가지며, 주변 색에 따라 달라 보인다. 강조 · 균형 · 공간을 만들고, 배색으로 조화나 불협화를, 쓰임에 따라 고유색 · 광학색 · 임의색, 감정과 상징을 전한다.',
    concepts: [
      { id: 'color.light', ko: '빛과 색 혼합', en: 'Color Theory: Additive and Subtractive', page: 256, body: '물체는 특정 파장을 반사할 뿐 스스로 색을 갖지 않는다. 빛의 삼원색(빨강 · 초록 · 파랑)은 섞을수록 밝아져 흰빛이 되고(가산), 물감은 섞을수록 빛을 덜 반사해 어두워진다(감산).' },
      { id: 'color.constancy', ko: '색 항상성', en: 'Color Constancy', page: 258, body: '빛에 따라 실제로 보이는 색이 바뀌어도 마음은 ‘잔디는 초록’이라고 고집하는 심리적 보정.' },
      { id: 'color.context', ko: '맥락의 영향', en: 'Color and Its Surroundings', page: 259, body: '같은 빛 아래서도 이웃한 색에 따라 색이 달라 보인다. 색은 홀로 보이지 않는다(알버스).' },
      { id: 'color.hue', ko: '색상', en: 'Hue', page: 260, body: '색의 이름(빨강, 주황…). 색상환에서 1차색 · 2차색 · 3차색으로 정리된다. 하나의 색상에서 수많은 색이 나온다.' },
      { id: 'color.value', ko: '색의 명도', en: 'Value (of Color)', page: 262, body: '색의 밝고 어두운 정도. 흰색을 섞으면 틴트, 검정을 섞으면 셰이드. 색마다 고유한 명도가 다르다(노랑은 밝고 파랑은 어둡다).' },
      { id: 'color.intensity', ko: '채도(강도)', en: 'Intensity (Chroma)', page: 264, body: '색의 순수함 · 포화도. 회색이나 보색을 섞으면 채도가 낮아져 탁한 톤이 된다.' },
      { id: 'color.afterimage', ko: '잔상과 동시 대비', en: 'Afterimage and Simultaneous Contrast', page: 265, body: '강한 색을 오래 본 뒤 흰 곳을 보면 보색이 떠오른다(잔상). 보색을 나란히 두면 서로를 더 강렬하게 만든다(동시 대비).' },
      { id: 'color.optical-mixture', ko: '시각적 혼합', en: 'Visual (Optical) Color Mixing', page: 268, body: '순색을 작은 단위로 나란히 놓아 눈이 섞게 하는 방법(점묘, 모자이크, 인쇄 망점, 화면 픽셀).' },
      { id: 'color.warm-cool', ko: '따뜻한 색과 차가운 색', en: 'Cool/Warm Colors', page: 270, body: '불 · 햇빛과 하늘 · 물의 연상에서 온 감각. 따뜻한 색은 앞으로, 차가운 색은 뒤로 물러나 보이며, 맥락에 따라 같은 색도 온도가 달라진다.' },
      { id: 'color.emphasis', ko: '색에 의한 강조', en: 'Color as Emphasis', page: 272, body: '색은 크기 · 형태 · 고립 같은 다른 강조 수단을 압도할 만큼 강하다.' },
      { id: 'color.balance', ko: '색과 균형', en: 'Color and Balance', page: 274, body: '선명한 색 한 점이 넓은 무채색 면적과 균형을 이룬다.' },
      { id: 'color.space', ko: '색과 공간', en: "Color's Spatial Properties", page: 276, body: '멀어질수록 채도가 낮아지고 푸른 회색이 되는 대기 원근. 반대로 색을 평면적으로 써서 공간 단서를 지우기도 한다.' },
      { id: 'color.monochromatic', ko: '단색 배색', en: 'Monochromatic', page: 278, body: '한 색상만 명도를 바꿔 쓰는 배색. 서로 다른 출처의 이미지를 하나로 묶고 형태와 질감을 부각한다.' },
      { id: 'color.analogous', ko: '유사색 배색과 색조', en: 'Analogous and Tonality', page: 279, body: '색상환에서 이웃한 색들의 배색. 하나의 색이 전체를 지배하는 색조(tonality)를 만든다.' },
      { id: 'color.triadic-complementary', ko: '3색 · 보색 배색', en: 'Triadic/Complementary', page: 280, body: '색상환에서 같은 간격의 세 색(삼각형), 혹은 마주 보는 두 색. 보색 배색은 대비가 강하다.' },
      { id: 'color.discord', ko: '불협화와 진동하는 색', en: 'Color Discord and Vibrating Colors', page: 282, body: '어울리지도 균형을 이루지도 않는 색의 조합. 명도가 같고 채도가 높은 빨강과 청록은 경계가 진동한다.' },
      { id: 'color.uses', ko: '고유색 · 광학색 · 임의색', en: 'Local, Optical, Arbitrary Color', page: 284, body: '고유색은 우리가 ‘아는’ 물체의 색, 광학색은 빛에 따라 실제로 보이는 색, 임의색은 감정 · 디자인을 위해 고른 색이다. 고유색을 과장한 것은 고조된 색(heightened color).' },
      { id: 'color.emotional', ko: '감정적 색', en: 'Emotional Color', page: 286, body: '형태를 읽기도 전에 색이 분위기를 만든다. 같은 색도 맥락에 따라 폭력이 되기도, 기쁨이 되기도 한다.' },
      { id: 'color.symbolism', ko: '색 상징', en: 'Color Symbolism', page: 288, body: '색이 추상적 개념을 대신하는 것. 문화마다 다르다(애도의 색, 왕실의 색, 신부의 색).' },
    ],
    pitfalls: [
      { title: '흑백 이미지도 색의 선택', body: '색을 지운 흑백은 무채색 혹은 단색 배색을 고른 것이다. ‘색을 소거해 형태에 집중시킨다’는 분석은 13장(단색 배색)과 12장(명도 패턴)으로 뒷받침할 수 있다.' },
      { title: '색수차', body: '렌즈의 색수차(chromatic aberration)는 책의 용어가 아니다. 가장자리에서 보색이 갈라져 진동하는 효과는 ‘진동하는 색’, 화면 전체의 디지털 질감은 ‘시각적 질감’으로 옮겨 쓸 수 있다.' },
    ],
    questions: ['색상 · 명도 · 채도 중 무엇이 가장 두드러지는가?', '배색은 단색 · 유사색 · 3색 · 보색 · 불협화 중 무엇인가?', '색이 강조 · 균형 · 공간 중 어떤 역할을 하는가?', '고유색인가, 빛에 따른 색인가, 임의로 고른 색인가?'],
    quiz: [
      { q: '가산 혼합과 감산 혼합의 차이는?', a: '빛은 섞을수록 밝아져 흰빛이 되고(가산), 물감은 섞을수록 어두워진다(감산).' },
      { q: '색의 세 속성은?', a: '색상(Hue), 명도(Value), 채도(Intensity/Chroma).' },
      { q: '임의색이란?', a: '자연의 색이 아니라 디자인 · 감정을 위해 주관적으로 고른 색.' },
    ],
  },
];
