/**
 * 블록 제목 — 대상(오브제) 이름 대신 그 이미지의 핵심 조형 장치로 짓는다.
 * Are.na 제목 형식: `번호. 한글 / English` (scripts/arena-push.mjs가 반영).
 * 이전 제목은 git 기록과 data/backup/에 남아 있다.
 */
export const titles: Record<number, { ko: string; en: string }> = {
  1: { ko: '그리드 위의 암시된 선', en: 'Implied Line on a Grid' },
  2: { ko: '흐린 윤곽의 보행', en: 'Blurred Outlines in Stride' },
  3: { ko: '방사하는 빛의 초점', en: 'Radiating Focal Light' },
  4: { ko: '여백을 가르는 실루엣', en: 'A Silhouette Cutting Negative Space' },
  5: { ko: '열린 형식의 곡선', en: 'Curvilinear Open Form' },
  6: { ko: '다가오는 손의 증폭된 원근', en: 'Amplified Reach' },
  7: { ko: '대비로 빛나는 초점', en: 'Focal Point by Contrast' },
  8: { ko: '명도가 된 선', en: 'Line Becoming Value' },
  9: { ko: '입자와 사라지는 윤곽', en: 'Grain and Lost Contour' },
  10: { ko: '형과 바탕의 반전', en: 'Figure-Ground Reversal' },
  11: { ko: '사라졌다 나타나는 윤곽', en: 'Lost-and-Found Contour' },
  12: { ko: '스케일의 환상', en: 'Fantasy of Scale' },
  13: { ko: '투명성 속 곡선과 직선', en: 'Curves and Edges in Transparency' },
  14: { ko: '머리를 감싸는 연속', en: 'Continuation Around the Head' },
  15: { ko: '부푼 곡선형의 외피', en: 'Swelling Curvilinear Shell' },
  16: { ko: '후광의 방사 균형', en: 'Radial Balance of a Halo' },
  17: { ko: '대칭 속 질감의 충돌', en: 'Texture Clash in Symmetry' },
  18: { ko: '관절의 변화된 반복', en: 'Varied Repetition of Joints' },
  19: { ko: '단색 배색의 투명 레이어', en: 'Monochrome Transparent Layers' },
  20: { ko: '겹침이 만든 명도 단계', en: 'Value Steps by Overlap' },
  21: { ko: '대칭과 점진적 리듬', en: 'Symmetry and Progressive Rhythm' },
  22: { ko: '직선형을 벗어난 곡선', en: 'A Curve Breaking the Rectilinear' },
  23: { ko: '명도로 잡은 초점', en: 'Focal Point by Value' },
  24: { ko: '사선과 열린 형식', en: 'Diagonal in Open Form' },
  25: { ko: '대칭의 생물형태', en: 'Symmetrical Biomorph' },
  26: { ko: '레가토로 이어진 연속', en: 'Legato Continuation' },
  27: { ko: '흐름 끝의 대비', en: 'Contrast at the End of a Flow' },
  28: { ko: '저대비로 겹친 면', en: 'Low-Contrast Overlapping Planes' },
  29: { ko: '생물형태와 시각적 질감', en: 'Biomorphs and Visual Texture' },
  30: { ko: '색면과 어긋난 윤곽선', en: 'Line Offset from Shape' },
  31: { ko: '굵기가 변하는 제스처', en: 'Gesture in Varying Weight' },
  32: { ko: '윤곽선과 제스처 붓질', en: 'Contour and Gestural Stroke' },
  33: { ko: '아래로 가라앉은 무게', en: 'Weight Sinking Low' },
  34: { ko: '속도를 띤 형태', en: 'Fast Shapes' },
  35: { ko: '다중 이미지의 박자', en: 'The Beat of Multiple Images' },
  36: { ko: '멈춘 동작의 대각선', en: 'Diagonal of Arrested Action' },
  37: { ko: '증폭된 원근의 보폭', en: 'Amplified Stride' },
  38: { ko: '방사하는 손가락의 초점', en: 'Radiating Fingers, Central Focus' },
  39: { ko: '줄기가 잇는 연속', en: 'Continuation Along a Stem' },
  40: { ko: '부풀린 비례의 반복', en: 'Repetition of Inflated Proportion' },
  41: { ko: '소실점에 선 작은 인물', en: 'A Tiny Figure at the Vanishing Point' },
  42: { ko: '반복을 깨는 고립', en: 'Isolation Breaking Repetition' },
  43: { ko: '그리드를 감싸는 곡선', en: 'Curves Around a Grid' },
  44: { ko: '근접으로 묶인 모듈', en: 'Modules Bound by Proximity' },
  45: { ko: '그리드 위의 점진적 리듬', en: 'Progressive Rhythm on a Grid' },
  46: { ko: '음형이 그리는 곡선', en: 'A Curve Drawn by Negative Space' },
  47: { ko: '드러난 내재선', en: 'Inherent Lines Revealed' },
  48: { ko: '겹침이 만든 꽃잎', en: 'Petals Made by Overlap' },
  49: { ko: '겹겹의 다중 리듬', en: 'Layered Polyrhythm' },
  50: { ko: '대기 원근 속 레가토', en: 'Legato into Atmosphere' },
  51: { ko: '사선의 스타카토', en: 'Diagonal Staccato' },
  52: { ko: '소리 나는 질감', en: 'Audible Texture' },
  53: { ko: '모호한 공간의 레이어', en: 'Layers of Equivocal Space' },
  54: { ko: '명도로 진행하는 리듬', en: 'Rhythm Progressing in Value' },
  55: { ko: '직선 틀 속 레가토', en: 'Legato in a Rigid Frame' },
  56: { ko: '각도의 점진적 리듬', en: 'Progressive Rhythm of Angles' },
  57: { ko: '저항의 운동감각', en: 'Kinesthetic Resistance' },
  58: { ko: '흔들리며 쌓인 리듬', en: 'A Swaying Stack' },
};

/** Are.na 제목 */
export const blockTitle = (no: number) => `${no}. ${titles[no].ko} / ${titles[no].en}`;
